stop using allModules and support for packed_array
chipsalliance/synlig pull request #2052
Opened 2023-10-07 03:39 UTC by alaindargelas

2023-10-09 04:59 UTC, alaindargelas commented
@kamilrakoczy , this is ready for review.

2023-10-10 15:54 UTC, kgugala requested changes

2023-10-10 15:54 UTC, kgugala commented on frontends/systemverilog/uhdm_ast.cc
> +
ditto

2023-10-10 15:54 UTC, kgugala commented on frontends/systemverilog/uhdm_ast.cc
> +        if (node && (node->type == AST::AST_STRUCT)) {
this looks like formatting change, please do not mix formatting and functional changes in single commit

2023-10-10 16:16 UTC, alaindargelas commented on frontends/systemverilog/uhdm_ast.cc
> +                        delete node;
This is the way these Lamda are all created. Check existing code line: 2823-2826 and 2838-2841. There are many pre-existing mini code snippet dupplication all over in the lambas. What is special about this one?

There is no nice way to describe what these 4 lines do in a function.

2023-10-10 16:25 UTC, alaindargelas commented on frontends/systemverilog/uhdm_ast.cc
> +            delete node;
It is not. The lamba payloads look similar but they are not exactly the same. Usage of Lamba is pervasive throughout the code, with very litle function factorization. This code is similar to existing code.

2023-10-10 17:33 UTC, kgugala requested changes

2023-10-10 17:33 UTC, kgugala commented on frontends/systemverilog/uhdm_ast.cc
> +                        delete node;
```suggestion
                 auto vpi_obj = vpi_get(vpiType, reg_h2);
                 if (vpi_obj == vpiStructVar || vpi_obj == vpiEnumVar || vpi_obj == vpiLogicVar) {
                     if (vpi_obj == vpiLogicVar)
                         current_node->is_logic = true;
                     visit_one_to_one({vpiTypespec}, reg_h2, [&](AST::AstNode *node) {
                         if (node->str.empty()) {
                             // anonymous typespec, move the children to variable
                             current_node->type = node->type;
                             current_node->children = std::move(node->children);
                         } else {
                             auto wiretype_node = new AST::AstNode(AST::AST_WIRETYPE);
                             wiretype_node->str = node->str;
                             current_node->children.push_back(wiretype_node);
                             current_node->is_custom_type = true;
                         }
                         delete node;
```

With this we can avoid code duplication + `vpi_get` will be called only once (unless I'm missing something)

2023-10-11 04:06 UTC, kgugala approved these changes

2023-10-11 04:07 UTC, merged