Alternative cmake build system
chipsalliance/synlig pull request #2089
Opened 2023-10-22 04:10 UTC by alaindargelas

2023-10-22 17:37 UTC, alaindargelas commented
@timkpaine FYI

2023-10-23 17:42 UTC, hzeller commented on makefile.txt
> +# MIT 2.0 License
I'd probably call this `cmake-makefile` or `cmake-makefile.txt` to emphasize that this is exercising that build path.

2023-10-23 17:43 UTC, hzeller commented on makefile.txt
> +SHELL := /bin/bash
Don't use hard-coded paths for shells (as they are not always installed there). Instead, call in `bash` for it to be found in the environment.

2023-10-23 19:02 UTC, pgielda commented
Just FYI @alaindargelas we will not merge without a review, nothing should be merged without a proper review. We will most likely review in the period of the next few days.

2023-10-23 19:09 UTC, kgugala requested changes

2023-10-23 19:09 UTC, kgugala commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
I don't like those hardcoded values. This cmake should take care of those and force setting them correctly for both Yosys and Synlig build, or calculate this during the build (not build scripts generation) by calling `yosys-config`

2023-10-23 19:21 UTC, alaindargelas commented on CMakeLists.txt
> +# MIT 2.0 License
Which license do you want, I can put anything.
Please state the text.

2023-10-23 19:22 UTC, alaindargelas commented on cmake-makefile
> +# MIT 2.0 License
Same as above, tell me what text you want.

2023-10-23 19:23 UTC, alaindargelas commented on cmake-makefile
> +ifeq ($(CPU_CORES),)
This is in Surelog and UHDM too, the make is a helper so developers don't have to type a cmake command line.

2023-10-23 19:37 UTC, kgugala commented on CMakeLists.txt
> +# MIT 2.0 License
it should be Apache-2.0 (the same as the rest of the code)

2023-10-23 19:39 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
Please read the comment above the flags. yosys-config cannot be called from Cmake, during cmake configuration, as cmake has not built yosys yet. 
This only applies for the local synlig build.

When synlig is embedded in a larger system that builds Yosys prior, then the $YOSYS_CONFIG is passed from above and and the hardcoded flags are not used.
This has been fully validated in a complex cmake build where synlig is just a component.

To be noted that the current Makefile build system of synlig is impossible to integrate in a larger build context where Yosys is not the one vendored by synlig.

This cmake fixes that.

2023-10-23 19:39 UTC, kgugala commented on CMakeLists.txt
> +  #set(MEM_SANITIZER_FLAGS
if this code is useful make it optional and controllable via e.g CMake cache, but do not leave random commented out code blocks without any explanation

2023-10-23 19:40 UTC, kgugala commented on cmake-makefile
> +ifeq ($(CPU_CORES),)
I proposed a build script - it will be convenient for devs and will not over complicate the flow

2023-10-23 19:45 UTC, kgugala commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
it cannot be called at the build files generation - this is true, but during the build you can call it (and you should if the flags are not provided). Otherwise we risk a situation when different parts of the lib will be build with different flags.

I understand that you use it with specific settings, but the code in this repo should be generic and usable by any users

2023-10-23 19:45 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
BTW: "or calculate this during the build (not build scripts generation) by calling yosys-config" is impossible to achieve in Cmake.

2023-10-23 19:46 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
yosys-config was just not though through to be integrated in the pure cmake build.
It needs some pre-build happening outside of cmake.

2023-10-23 19:55 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
I don't know how to practically do that: "but during the build you can call it (and you should if the flags are not provided)."
Please point to a sample code that does that. Or submit an amendment to this PR.

2023-10-23 19:55 UTC, kgugala commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
`yosys-config` is just a program, you can call any arbitrary program during the build stage (and please stop resolving comments that are not resolved)

If you don't want to call `yosys-config` during build stage, please ensure that both Yosys and Synlig are built with the same flags (force the same flags for both, do not hardcode them for just one part)

2023-10-23 19:58 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
You can't read back any output of such program and re-inject in CMake vars. at least I don't know how to do that.

2023-10-23 20:03 UTC, alaindargelas commented on cmake-makefile
> +ifeq ($(CPU_CORES),)
I don't see the complication.
Developers type:

make -f cmake-makefile

instead of the complex cmake command line while developing.
This has worked fine in Surelog and UHDM, where the command is simply "make"
In this case it has to be make -f cmake-makefile since there is another Makefile.

2023-10-23 20:04 UTC, alaindargelas commented on cmake-makefile
> +ifeq ($(CPU_CORES),)
I removed all the commented out code. I'll let the package maintainers bring it back if they need it.

2023-10-23 21:03 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
I minimized the hardcoding to: 

set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os")

2023-10-23 22:38 UTC, alaindargelas commented on cmake-makefile
> +ifeq ($(CPU_CORES),)
@kgugala , can you add @timkpaine as a contributor as he might want to add-on to that CMakeLists.txt

2023-10-24 00:17 UTC, hzeller commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
could the flags be something like  something that evaluates on the shell later as an invocation of `yosys-flags` ? I find it very relevant to be able to compile on different platforms.

Wouldn't back-ticking it already help ? E.g. if `--cxxflags` are the relevant flags:
```
set(YOSYS_CONFIG_FLAGS, "`yosys-config --cxxflags`")
```

2023-10-24 01:38 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
In CMake to build on different platform you explicitly specify the flags for that platform in the CMakeLists.txt. 
You don't get the flags from an external step.
See Surelog/CMakeLitsts.txt. It has all the flags for all the platforms and it works.

When the time comes to make those specific flags platform dependent, I trust the interested party will make the adjustments to support the equivalent to -fPIC and so on.

2023-10-24 01:40 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
"Wouldn't back-ticking it already help ? E.g. if --cxxflags are the relevant flags:"  
It that even worked, it would happen at the wrong time: the cmake configuration time.
Yosys, in this repo, is not built yet by configuration time, it is build at "build time".
See cmake configuration time vs build time.

2023-10-24 04:18 UTC, hzeller commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
it is passed to the command line of the compiler. So when we build, the compiler command line is invoked with that back-ticked part, which then expands to the necessary flags.

2023-10-24 04:39 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
yosys-config does not exist when you call it.
The old chicken and egg pb.
Please try yourself this PR and your suggested changes, you'll see they don't work.

2023-10-24 06:27 UTC, hzeller commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
mmh, I assumed that `Synlig` has a dependency on `Yosys`, so that would be built first before the first Synlig build can proceed.

After all, you only can compile Synlig with the Yosys headers once that has been put in the build directory. I imagine one would put a build-dependency accordingly (it is like building capn-proto first before being able to run the capnp compiler). This is what build systems are usually good at, so I am surprised that it is so hard with CMake.

It sounds like you also build Yosys with CMake ? In that case you probably have the resulting binaries (such as `yosys` and `yosys-config` and the includable headers) declared somewhere in its output specification. Would it be possible to take the dependency on that ?

I don't know CMake enough to provide a suggestion (the backtick thing was just a suggestion to move the evaluation to the build time and it worked in my experiment), but there might be proper ways to do that in CMake. I leave it to the experts.

2023-10-24 15:55 UTC, kgugala commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
this is one option, but I really don't insist on that - there is the second one I suggested (which should be easier to implement):

Declare all the required flags as variables (can be even controlled with CMake cache) and force them for both parts - Yosys and Synlig. I just want to avoid a situation where the default build flags in Yosys change and we'll have them hardcoded for Synlig (this always ends up with bugs which are really hard to track).

You can overwrite Yosys build config by providing the `Makefile.conf` and defining all the params you need. The conf file is included here https://github.com/YosysHQ/yosys/blob/master/Makefile#L64C22-L64C22

2023-10-24 17:25 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
I pushed a new change:
set(YOSYS_CONFIG_FLAGS "-D_YOSYS_")

The **only** hardcoded flag is now: -D_YOSYS_, this flag is never going to change in Yosys. No need to fear this: "avoid a situation where the default build flags in Yosys change and we'll have them hardcoded for Synlig"
  
We don't need any of the convoluted solutions above. We have a self-contained Cmake that does all the job.
Just to make sure you understand, this flag is used to compile the synlig code, not the Yosys code.
Both synlig and Yosys are built concurently by cmake.

2023-10-24 21:59 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
Opentitan fails on its own with the latest run. This PR is bringing no changes from Surelog whatsoever.

2023-10-25 18:28 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
@kgugala are we done addressing your concerns? Can we get this merged?

2023-10-25 19:14 UTC, pgielda commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
Can you stop pinging maintainers every 5 minutes? We are in a different timezone and also this is not the only thing we so 24/7. As for OpenTitan -- there is a fix for OpenTitan waiting for the CI to be green. Please be patient. 
As for buildsystem -- definitely there are still concerns, also its not that we planned to have 5 different buildsystems. You can maintain your own buildsystem in your own repo for now while we analyze if this should go in to Synlig... and definitely not in the form it is now...
Again the only system we officially support is Debian.

2023-10-25 19:19 UTC, alaindargelas commented on CMakeLists.txt
> +set(YOSYS_CONFIG_FLAGS "-MD -MP -D_YOSYS_ -fPIC -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/local/include -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TC
The current build system is inadequate for a lot of the use cases. I'll maintain (and others) this cmake based build system.

2023-10-26 09:52 UTC, kgugala commented on CMakeLists.txt
> +      DEPENDS ${PROJECT_SOURCE_DIR}/third_party/yosys/kernel/yosys.cc
maybe we can do sth like here https://github.com/openxla/iree/issues/6434 and check for the required submodules and inform the users if they are not.

2023-10-26 09:59 UTC, kgugala commented
I think we're almost ready to merge this just 2 small requests:

1) can you run a [cmake-format](https://cmake-format.readthedocs.io/en/latest/cmake-format.html) on the files? Indentation seems to be a little inconsistent. I suppose it makes sense to even include cmake format checks in CI so any future updates will keep correct formatting

2) please rebase the PR on top of main (where the OpenTitan issue is fixed), so we can have green CI here

2023-10-26 17:05 UTC, alaindargelas commented on CMakeLists.txt
> +      DEPENDS ${PROJECT_SOURCE_DIR}/third_party/yosys/kernel/yosys.cc
Done: 
  if(NOT EXISTS "${PROJECT_SOURCE_DIR}/third_party/surelog/.git"
     OR NOT EXISTS "${PROJECT_SOURCE_DIR}/third_party/yosys/.git")
    message(SEND_ERROR "The git submodules are not available. Please run
      git submodule sync
      git submodule update --init --recursive third_party/{surelog,yosys}")

2023-10-26 17:05 UTC, alaindargelas commented on CMakeLists.txt
> +# The initial content of YOSYS_CONFIG_FLAGS is a bootstrap that enables to build the synlig local code (frontends/systemverilog), not yosys itself.
Done

2023-10-26 17:05 UTC, alaindargelas commented
Rebased and formatted.

2023-10-27 04:26 UTC, kgugala approved these changes

2023-10-27 04:26 UTC, merged