Fix bug with typespecs declared in package
chipsalliance/synlig pull request #2097
Opened 2023-10-23 21:14 UTC by alaindargelas

Fixes issue #1859 which is a major bug.

2023-10-25 09:34 UTC, kbieganski requested changes
Looks OK, let's just stick to the naming convention.

2023-10-25 09:34 UTC, kbieganski commented on frontends/systemverilog/uhdm_ast.cc
> +    bool anonymousTypespec = false;
```suggestion
    bool anonymous_typespec = false;
```

2023-10-26 04:22 UTC, kgugala commented
It seems there are conflicts here @alaindargelas can you rebase this PR so we can merge it?

2023-10-26 17:39 UTC, alaindargelas commented
PR #2072 fixed this problem too.
So the code change in this PR is no longer needed (Actually does not work anymore as-is).
I removed the code change, this PR is only a new testcase to prevent future regression.

2023-10-26 17:57 UTC, kgugala approved these changes

2023-10-27 04:28 UTC, merged