Make compile for Yosys 0.37
chipsalliance/synlig pull request #2300
Opened 2024-01-26 05:44 UTC by hzeller

Yosys added another parameter to AST::process(), which we have to track.

Unfortunately, there is no easy way to #ifdef on a yosys version that I know of (there do not seem to be macros exposed), so this will not compile with old versions anymore.

Fixes #2299

2024-01-26 05:56 UTC, hzeller commented
Of course, the build will now fail as it assumes Yosys 0.36.
If there is a way to detect the Yosys version with a macro, please advise, then I can make it work for both versions.
If not easily, then I suggest to just roll forward to use 0.37

2024-01-26 10:12 UTC, pgielda commented
Yosys version seems to be a variable in its Makefile: https://github.com/YosysHQ/yosys/blob/master/Makefile#L144
We could potentially try to somehow leverage that

2024-01-26 10:12 UTC, pgielda commented
FYI @tgorochowik @kgugala

2024-01-26 16:26 UTC, tgorochowik commented
@hzeller at this point I think it might be worth considering analyzing the yosys binary we're building with, extracting the mangled symbol and calling it with `dlsym`

I pushed a simple PoC here:
https://github.com/chipsalliance/synlig/commit/8c4e1eee052a7ae06aa2c1f0537f5956f35aa799

The implementation above works on my machine with both old and new yosys, but it's obviously not universal, because symbol mangling might differ between compilers, but the symbols could be checked with `nm` in Makefile and propagated through a define if we go with a similar idea.

Another thought I have is using a weak symbol with all arguments that would call the original symbol with fewer arguments (and a weak empty symbol without the extra argument so it still compiles with new yosys), but I'm not sure this can be simply pushed to an external namespace, might be worth an experiment.

2024-01-26 17:28 UTC, alaindargelas requested changes
@hzeller , please update yosys in this PR too. It currently breaks as you are still using the previous yosys.
PS, I would not worry about backward compatibility.

2024-01-26 18:41 UTC, tgorochowik commented
> PS, I would not worry about backward compatibility.

Good point, in general I agree, however I think latest changes in yosys (before the API change) broke some regression tests in the plugin. These might need to be fixed before we can bump yosys

2024-01-27 04:14 UTC, alaindargelas commented
@hzeller all the failures probably require porting all the changes happening in:
https://github.com/YosysHQ/yosys/compare/ea7818d31bb2533d4ecceb2ed1bcf4a22b850453...80511ced71b657e77a5389d54c6aa045c047ccaf#diff-9cf03955fa6ed7051b83cfb95de9e3c42eeeecdff3fa071fbb14ac43e41b12a0

To:

./third_party/yosys_mod/synlig_simplify.cc

2024-01-27 16:42 UTC, hzeller commented
Yeah, it looks like we can only strictly move forward with only marginal backward compatibility.

I have not tracked that, how is synlig_simplify.cc different from the origin it was coming from ? Unfortunately, all version information is lost that it would be possible to see what is different.
Moving forward, it would probably be a good idea to also add the commit hash a synlig_simplify.cc was derived from yosys.

2024-01-27 16:57 UTC, hzeller commented
These were the last relevant changes in the synlig_simplify.cc
https://github.com/chipsalliance/synlig/commit/f97999d402241a50ddea4dd4e45011e06bd2c37f
https://github.com/chipsalliance/synlig/commit/c5bd73595151212c61709d69a382917e96877a14

So change in simplify.cc in yosys are

git diff -uw -r 8367f06188edf750b32bd603552ba9d75995baf5 -r 80511ced71b657e77a5389d54c6aa045c047ccaf frontends/ast/simplify.cc

...

2024-01-27 18:58 UTC, alaindargelas commented
The problem is much larger than that.
This file is essentially a hard fork of the Yosys simplify.cc,
here is an example of diff, the 2 bodies of the same function have diverged considerably.

![Screenshot from 2024-01-27 10-50-36](https://github.com/chipsalliance/synlig/assets/63669492/88d9d747-ea8f-4c66-a984-701ad8abc629)

To checkout the repo before the file name change:

git checkout 01111c512ced3faaeae12a875e7a21f115580c63
git submodule update --recursive
Then you can perform the diff.

The Antmicro guys had a methodology to merge-in changes as the one your pointed out above. Please check with them if they can help.
It's a 3-way diff merge that has to happen essentially.

2024-01-29 15:49 UTC, tgorochowik commented
It's possible that it's a matter of backporting the changes from simplify. It's not possible to say for certain without an actual analysis of the new errors (or without actually doing this). I still think having a slim compatibility layer to not have to deal with that each time API changes could be beneficial (of course I agree it'd be better to just fix those issues, but having sth to unblock you until this is done would be nice).

@hzeller since you didn't like the dlsym approach, PTAL at a simple workaround with the use of weak linking: https://github.com/chipsalliance/synlig/commit/dc75266d965105a96ac9b3345d8dc20967c0358e - it works for me both with old and new yosys. Of course it has it's own limitations (i.e. not all platforms support weak linking), if something similar breaks in the future adding extra wrappers similar to this one should be super quick.

2024-03-03 20:31 UTC, hzeller commented
I think I like the weak-linkage approach  in 
https://github.com/chipsalliance/synlig/commit/dc75266d965105a96ac9b3345d8dc20967c0358e better @tgorochowik 

Can you format it neatly like I did in this PR with comments on what these values are ? It is super-confusing and easy to miss what the n'th boolean means :)

2024-08-07 07:35 UTC, kamilrakoczy commented
Solution with compatibility layer was merged in: https://github.com/chipsalliance/synlig/pull/2357
and now we merged PR that is updating yosys 0.44 version (current upstream): https://github.com/chipsalliance/synlig/pull/2510

This PR isn't needed anymore, closing.

2024-08-07 07:35 UTC, closed without merging